### ISSUE TITLE
Anthropic Claude: Invalid Request. There was an issue with the format or content of your request.

### ISSUE THREAD

**Issue by martinhoess** [valentinfrlch/ha-llmvision#48] opened 2024-08-12 09:42 UTC
### Bug Description

Can't use Anthropic Claude with image or image entity

**Version**: v1.0.2
Home Assistant Core 2024.7.4

### Service Call

```yaml
service: llmvision.image_analyzer
data:
  provider: Anthropic
  max_tokens: 250
  temperature: 0.5
  model: claude-3-5-sonnet-20240620
  message: Describe what you see?
  image_file: /config/www/tmp/example.jpg
  target_width: 1000
```

### Logs

```
2024-08-12 11:29:43.054 DEBUG (MainThread) [custom_components.llmvision.request_handlers] Base64 Images: ['<long_string>']
2024-08-12 11:29:43.054 INFO (MainThread) [custom_components.llmvision.request_handlers] Request data: {'model': 'claude-3-5-sonnet-20240620', 'messages': [{'role': 'user', 'content': [{'type': 'text', 'text': 'Image 1:'}, {'type': 'image', 'source': {'type': 'base64', 'media_type': 'image/jpeg', 'data': '<long_string>'}}, {'type': 'text', 'text': 'Describe what you see?'}]}], 'max_tokens': 250, 'temperature': 0.5}
2024-08-12 11:29:44.022 DEBUG (MainThread) [custom_components.llmvision.request_handlers] Provider: anthropic
2024-08-12 11:29:44.022 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Error for call_service at pos 1: Invalid Request. There was an issue with the format or content of your request.
2024-08-12 11:29:44.023 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140278611944080] Invalid Request. There was an issue with the format or content of your request.
```

**Comment by martinhoess** [comment] 2024-08-12 16:51
Just tried the older 0.4.7 version and it works fine (same service call data)

**Comment by valentinfrlch** [comment] 2024-08-12 20:09
I've been able to replicate the error. Not sure where the problem is, but this is definitely an issue. Thanks for pointing it out!

**Comment by valentinfrlch** [comment] 2024-08-14 18:46
Should be fixed now. Thanks again for pointing it out!

**Closed by valentinfrlch** 2024-08-14 18:46 UTC
Labels: bug
