### ISSUE TITLE
Azure OPen Ai integracion

### ISSUE THREAD

**Issue by kiloptero** [valentinfrlch/ha-llmvision#88] opened 2024-11-14 03:04 UTC
**Is your feature request related to a problem? Please describe.**

Its possible to use azure open ai?
**Describe the solution you'd like**

Trying with custom open ai without work. Using the Endpoint URL!
**Describe alternatives you've considered**

**Additional context**

**Comment by valentinfrlch** [comment] 2024-11-14 17:04
Closing as this is a duplicate of #64

**Closed by valentinfrlch** 2024-11-14 17:04 UTC
